### ISSUE TITLE
unable to add backup channels to primary active channel

### ISSUE THREAD

**Issue by grooverider2016** [Threadfin/Threadfin#104]
![Screenshot 2023-07-03 135431](https://github.com/Threadfin/Threadfin/assets/22882057/7c131983-3980-48a5-97ef-d9ef3069e271)
![Screenshot 2023-07-03 135915](https://github.com/Threadfin/Threadfin/assets/22882057/6aa33c28-f763-4a51-be8f-8625027d4e04)
![Screenshot 2023-07-03 140311](https://github.com/Threadfin/Threadfin/assets/22882057/d10c14ca-5a6e-428b-a36a-d6fa60987607)
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**

**Server (please complete the following information):**
- OS Windows 11
- Arch Intel 64 bit
- 1.0 (13)

**To Reproduce**

select a channel in mapping tab. 
check box to make active
select xml guide to use
select guide for that channel
click to add backup channel but instead of listing channels here it simply shows the xml epg data associated to channel name. Used to show channels themselves.

**Expected Behaviour**

When i click on backup channel i expect it to show the list of available channels from my provider as it used to in earlier versions of threadfin. Instead in the last few versions it has shown the epg data mapped to channels. This means that I cannot add additional streams as backup channels anymore as I am using custom XML provided by SD. Please allow it to just list the available channels rather than channels that have associated epg data.

I used to be able to choose a channel and then add backup channels to the primary channel and then select the guide and EPG data for the primary channel. 
I've attached 2 screenshots form threadfin 1.0 (3) showing the way it shows channels (No epg data associated) and one screenshot of threadfin 1.0 (13) where it shows it based on guide/epg name so doesnt list the additional streams.

**Comment by grooverider2016** [comment]
Is this one that can be looked into? Only way i can add channels otherwise is to roll back to 1.0 (3), map in the backup channels and then go back to 1.0 (13)

**Comment by JHeat** [comment]
Having the same issue here. Moreover, I get inconsistent results when checking urls.json - a majority of the time the backup urls aren't updated. I'm unsure what to do??

**Comment by steamyRayV** [comment]
For me I danced around the releases and found that version 10 allowed me to add backups. I rolled back to do setup then I plan to update and give this a try when there a release that adds a failover for a hitting a tuner limit.

**Comment by Fyb3roptik** [comment]
This should be fixed in 1.0.14 Let me know if it is not

**Comment by iceman73** [comment]
This issue is back in 1.0 (16)

**Comment by Fyb3roptik** [comment]
Does your EPG have a display-name attribute? If not can you paste in an example of your epg data? This works off of the display-name attribute

**Comment by iceman73** [comment]
yes it does

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

<tv source-info-url="http://tvlistings.zap2it.com/" source-info-name="zap2it.com" generator-info-name="zap2xml" generator-info-url="zap2xml@gmail.com">
        <channel id="I1.91035.zap2it.com">
                <display-name>1 WINS</display-name>
                <display-name>1</display-name>
                <display-name>WINS</display-name>
                <icon src="https://zap2it.tmsimg.com/sources/generic/generic_sources_h3.png" />
        </channel>
        <channel id="I2.114483.zap2it.com">
                <display-name>2 DTV203</display-name>
                <display-name>2</display-name>
                <display-name>DTV203</display-name>
                <icon src="https://zap2it.tmsimg.com/sources/generic/generic_sources_h3.png" />
        </channel>

Example of M3U
#EXTM3U
#EXTINF:-1 channel-id="5.1" channel-number="5.1" tvg-name="WRAL HD",5.1 WRAL HD group-title="antenna"
http://192.168.94.118:5004/auto/v5.1
#EXTINF:-1 channel-id="5.2" channel-number="5.2" tvg-name="WRAL DT",5.2 WRAL DT group-title="antenna"
http://192.168.94.118:5004/auto/v5.2
#EXTINF:-1 channel-id="5.3" channel-number="5.3" tvg-name="WRAL 3",5.3 WRAL 3 group-title="antenna"
http://192.168.94.118:5004/auto/v5.3
#EXTINF:-1 channel-id="5.4" channel-number="5.4" tvg-name="WRAL 4",5.4 WRAL 4 group-title="antenna"
http://192.168.94.118:5004/auto/v5.4
#EXTINF:-1 channel-id="11.1" channel-number="11.1" tvg-name="WTVD-D1",11.1 WTVD-D1 group-title="antenna"
http://192.168.94.118:5004/auto/v11.1
#EXTINF:-1 channel-id="11.2" channel-number="11.2" tvg-name="LOCLish",11.2 LOCLish group-title="antenna"
http://192.168.94.118:5004/auto/v11.2
#EXTINF:-1 channel-id="11.3" channel-number="11.3" tvg-name="thisTV",11.3 thisTV group-title="antenna"
http://192.168.94.118:5004/auto/v11.3
#EXTINF:-1 channel-id="11.4" channel-number="11.4" tvg-name="HSN",11.4 HSN group-title="antenna"
http://192.168.94.118:5004/auto/v11.4

**Comment by Fyb3roptik** [comment]
That is the m3u. I need to see the EPG along with the channel info in the epg

**Comment by iceman73** [comment]
EPG

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

<tv source-info-url="http://tvlistings.zap2it.com/" source-info-name="zap2it.com" generator-info-name="zap2xml" generator-info-url="zap2xml@gmail.com">
        <channel id="I1.91035.zap2it.com">
                <display-name>1 WINS</display-name>
                <display-name>1</display-name>
                <display-name>WINS</display-name>
                <icon src="https://zap2it.tmsimg.com/sources/generic/generic_sources_h3.png" />
        </channel>
        <channel id="I2.114483.zap2it.com">
                <display-name>2 DTV203</display-name>
                <display-name>2</display-name>
                <display-name>DTV203</display-name>
                <icon src="https://zap2it.tmsimg.com/sources/generic/generic_sources_h3.png" />
        </channel>
        <channel id="I4.11939.zap2it.com">
                <display-name>4 WUNC</display-name>
                <display-name>4</display-name>
                <display-name>WUNC</display-name>
                <icon src="https://zap2it.tmsimg.com/h3/NowShowing/11939/s11039_ll_h15_ab.png" />
        </channel>
        <channel id="I4.30645.zap2it.com">
                <display-name>4 WUNCDT</display-name>
                <display-name>4</display-name>
                <display-name>WUNCDT</display-name>
                <icon src="https://zap2it.tmsimg.com/h3/NowShowing/30645/s32356_ll_h15_ac.png" />
        </channel>
        <channel id="I5.11809.zap2it.com">
                <display-name>5 WRAL</display-name>
                <display-name>5</display-name>
                <display-name>WRAL</display-name>
                <icon src="https://zap2it.tmsimg.com/h3/NowShowing/11809/s10991_ll_h15_ad.png" />
        </channel>

**Comment by grooverider2016** [comment]
I don't think we want to see the epg at all. For the backup channels we want to see the channel list. Currently it shows the epg as mapped to a channel. If you are using m3us sourced from an iptv provider and then using an epg from the likes of SD then they don't map automatically. I'm combining multiple epgs from SD using epg123 to get 14 day guide info as my iptv provider only supplies 2 day epg data for it's channels. Can we have the option for the backup channels to just list the channels in the drop down, not the epg please?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iceman73** [comment]
Agree with @grooverider2016 as I have 4 different EPGs I use to get my schedules right

**Comment by bctripster** [comment]
That might explain my issue, I'm just using an install for proxying sources to receive with https enabled so I'm not loading an EPG into threadfin for the few channels I'm doing it for and I can't get the backup to do anything but be the last URL in the m3u playlist. Yes please just have it pull from the channel list rather than looking for an EPG listed channel, especially when we may use the dummy EPG for them and let the client pull in EPG data from other sources.

**Comment by grooverider2016** [comment]
It used to do just the channel list for backup channels. We dont really need to do it via epg as we have already selected an epg lineup for the primary channel so we only really need to list by alternative channels not by epg matched channels
________________________________

**Comment by steamyRayV** [comment]
I agree, seeing the channel names from the m3u seems intuitive to me. 
I would like to add that channels which match the tvg-id tag of an active channel could be automapped as backups. We could format our m3u's and not have to do any matching inside Threadfin. Would that make sense as a feature request? It could also be exactly matching channel names, it wouldn't have to be tvg-id.

**Comment by Fyb3roptik** [comment]
Fixed in 1.0.20

**Comment by grooverider2016** [comment]
> Fixed in 1.0.20

still showing EPG mapped, not just channels list (1.0.22). Not fixed

**Comment by grooverider2016** [comment]
> That is the m3u. I need to see the EPG along with the channel info in the epg

for backup channels we dont want to be referencing epg info at all. the epg data is already selected via the primary channel. we now simply want to select other streams that may or may not have epg data mapped but are showing the same thing. in my example for instance i want BT Sports 1 HEVC FHD as primary, i map that to the correct guide source and data then i use BT Sport 1 FHD, BT Sport 1 HD and possibly BT Sport 1 SD as backup channels. I dont have the HD and and SD channels active or epg mapped in general so they dont show up when I'm searching them as the dropdown for each backup channel only shows channels that have epg data mapped to them. Threadfin 1.0.3 was the last version that listed the channels as is (1st screenshot in OP) Please reinstate this method/view going forward.

**Comment by grooverider2016** [comment]
> This still works the same way, the choices for backup channel are the tvg-id that the channel is assigned.
> 
> Such as this (Name - tvg-id):
> 
> PBS Main - PBS.us PBS backup1 - PBS.us PBS backup2 - PBS42.us PBS backup3 - WFKL.us
> 
> The names don't matter but the tvg-id that is assigned to your backups does. Whatever tvg-id they are set to is what you type in the backup channels on the main channel mapping. You can also assign all the backups to the same tvg-id as the main and then just put that tvg-id in all the backup slots.
> 
> You can verify backups are set by checking urls.json after saving mapping.

but having to type the whole tvg-id in to get a backup channel is a pain in the arse and very long winded. Was much simpler when it simply showed a list of the channels/streams in the M3U. all you needed to do was type the first few letters and it showed all available streams that matched. currently if you dont have the right epg selected and if the channel/stream doesnt have an epg mapping assigned then it doesnt show. Needs to go back to the previous way of just listing all channels/streams from the M3U's that are active and filtered.

**Comment by emanuellopes** [comment]
I have the same issue, when I'm trying to add another channel as backup, Only appearing the items from epg.

I tried just copy and paste the backup channel name, but inside urls.json file, the backup channel still empty
