### ISSUE TITLE
strconv.Atoi parsing ---- invalid syntax () - EC: 0

### ISSUE THREAD

**Issue by jaretclifton** [Threadfin/Threadfin#107]
**Describe the bug**
Throughout the log files a similar message is displayed for a multitude of entries regarding strconv.Atoi having an invalid syntax while parsing channels when creating the guide.

**Server (please complete the following information):**
- OS: Linux - Ubuntu 22.04
- Arch amd64
- Threadfin Version 1.0 Build: 8

**To Reproduce**
1. Add IPTV channels
2. Use mapping to enable channel
3. Set guide for channel to be a dummy channel

**Expected behavior**
Errors are not seen in the log

**Comment by Fyb3roptik** [comment]
Fixed in 1.0.14

**Comment by jaretclifton** [comment]
Updated to 1.0.16 and still receive the error:

[ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
[ERROR] strconv.Atoi: parsing "NGHDANZ": invalid syntax () - EC: 0
[ERROR] strconv.Atoi: parsing "HCLCHEN": invalid syntax () - EC: 0

**Comment by jaretclifton** [comment]
Seeing these pop up in the log files again. On version 1.0.22

[ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0

**Comment by RohirrimRider** [comment]
This is still a problem in the latest version 1.0.24.

2024-03-09 20:27:24 [Threadfin] [ERROR] strconv.Atoi: parsing "bssw.us": invalid syntax () - EC: 0

It seems that using Threadfin Dummy with a channel requires an integer? But it automatically populates as a string so it's not clear to me why.

**Comment by chminsc** [comment]
still reporting this problem in lastest version
