### ISSUE TITLE
Backup channels no longer working

### ISSUE THREAD

**Issue by d3m1s33** [Threadfin/Threadfin#116]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Backup channels are no longer being set properly/do not function, and seem to act strange, see screenshots.

When backups are added it only actually adds 1 backup the urls.json file, in the slot for the 3rd backup. While in mapping it will display only the 1st and 2nd backup streams correctly and rewrites the name of the 3rd backup to the 2nd backup name after you save.

**Server (please complete the following information):**
- OS Linux - Ubuntu
- Arch Intel 64 Bit
- Threadfin Version and Build [to be found in the Threadfin log] 1.0 (16) Main

**To Reproduce**

How things are named in my setup:
(use screenshots to understand this)

Main channel:
—Threadfin name: PBS.us
—M3U name: PBS.us (8)
—EPG name: PBS.us

Backup channels (all same just change number):
—Threadfin name: PBS.us (b1)
—M3U name: PBS.us (b1)
—EPG name: N/A this is not mapped to EPG prior to Threadfin or within Threadfin

**Expected behavior**
The stream URLs from the 3 selected backup channels are incorporated properly.

**Screenshots**

in the urls.json file:
![image](https://github.com/Threadfin/Threadfin/assets/126936458/9d876118-c0d6-471a-b5b1-97df86188933)
in mapping:
![image](https://github.com/Threadfin/Threadfin/assets/126936458/2cd836d4-4486-4ef1-950b-8c73b3332b4d)

**Comment by Fyb3roptik** [comment]
fixed in 1.0.20

**Comment by flippz** [comment]
Im having the same BUG in 1.0.26.. Was it not fixed after all?
