### ISSUE TITLE
Windows 1.1.4 and beyond do not start

### ISSUE THREAD

**Issue by bweezy21** [Threadfin/Threadfin#255]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Threadfin fails to start on windows

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu] Windows
- Arch [e.g. Intel 64 Bit] Intel 64 Bit
- Threadfin Version and Build [to be found in the Threadfin log] 1.1.4, 1.1.5, 1.1.6

**To Reproduce**
1. Update Threadfin to 1.1.4 or newer
2. Start up windows service
3. Threadfin never starts

**Expected behavior**
Threadfin to start

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 124

**Additional context**
Reverting back to 1.1.3 works as expected.

**Comment by bweezy21** [comment]
so to add context the app does start but it is binding itself to wsl network interface (172.30.80.1) and that interface is not access on the host machine via localhost for whatever reason, it is accessible via 172.30.80.1:34400/web/. 1.1.3 binds to the same 172.30.80.1 interface but is accessible via localhost.

**Comment by Fyb3roptik** [comment]
Fixed in 1.1.8

**Comment by bweezy21** [comment]
> Fixed in 1.1.8

Not fixed. Still chooses WSL interface when running as a windows service via exe.

![image](https://github.com/Threadfin/Threadfin/assets/8197439/74622573-a653-4bba-9170-84ce53f89e4a)
