### ISSUE TITLE
Zombie Mappings

### ISSUE THREAD

**Issue by JRGonz** [Threadfin/Threadfin#374]
**Describe the bug**

Some channels keep adding inactive channels when the m3u is updated (unless automatic mapping is enabled) even though the channel still appears in the list and active and mapped. I also have one where I removed it from the list and it lingers at the bottom as inactive even though it is no longer in threadfin.m3u. I tried viewing the web interface using a private browser just to ensure it wasn't a browser cache issue. 

**Server (please complete the following information):**
- OS Debian 12 container running under Proxmox 8.2.4
- Arch AMD 3700x (x64)
- Threadfin Version and Build Version 1.2 (7)
- 
**To Reproduce**
1. Add m3u.
2. Map channels.
3. Refresh m3u / playlist. 
4. Seems a bit random.

**Expected behavior**
The expected behavior is that there will be one copy of the active channel in the map list. Also, if a channel is removed from the m3u it should no longer be listed. 

**Desktop (please complete the following information):**
 This problem is unrelated to the client(s).

**Comment by Fyb3roptik** [comment]
What version are you on?

**Comment by JRGonz** [comment]
> What version are you on?

1.2 build 7

**Comment by NvrBst** [comment]
I also see this, I was on 1.2 build 6, but I upgraded to 1.2 build 7, and it is doing the same. There are zombie channels in the MAPPING section, which say active, which are no longer in the Active Streams list...

Also Filtered Active Channels say (165 / 4349), and my Mapped Channels (147)... but 18 unmapped channels do not appear anywhere... they do not show up in the bottom of the MAPPING section (where the unmapped channels used to go).
I can see the unmapped channels in the FILTER section, in the "Active Streams" list, but can't select them.

I'm using the windows_amd64   server.  I have 0 errors and 0 warning showing up in the logs.

**Comment by propho** [comment]
Have you tried deleting the filter then recreating?  This was how I fixed my issue which I believe was introduced prior to 1.2.7.  I don't think the issue comes back after.

**Comment by 2esq** [comment]
> Have you tried deleting the filter then recreating? This was how I fixed my issue which I believe was introduced prior to 1.2.7. I don't think the issue comes back after.

Yes, didn't work.

**Comment by Fyb3roptik** [comment]
Fixed in 1.2.8

**Comment by 2esq** [comment]
> Fixed in 1.2.8

I still face the same issue.
Redid all the filters and as soon as I start editing/renaming/sorting channels, some disappear from the m3u file but as visible as mapped in the threadfin gui

**Comment by Fyb3roptik** [comment]
Fixed in 1.2.9
