### ISSUE TITLE
Some channel renaming fails and reverts to original channel name

### ISSUE THREAD

**Issue by jaretclifton** [Threadfin/Threadfin#386]
Describe the bug
Even as of version 1.2.7 some renamed channels revert to provider naming.

Server (please complete the following information):

OS Ubuntu
Arch 64-bit
Threadfin Version and Build 1.2.7
To Reproduce

Change "Channel Name"
Save mapping
Refresh channels from provider
Channel name will revert
Expected behavior
Renamed channel information retained.

Screenshots
N/a

Desktop (please complete the following information):

OS: Windows
Browser: Chrome
Additional context
Some channels seem to allow renaming, others simply revert.

**Comment by Fyb3roptik** [comment]
Fixed in 1.2.8

**Comment by theharumph** [comment]
I still see the bug on build 1.2.8 running in a Docker container.

From my troubleshooting, the bug may be specific to channels which have a Threadfin generated tvg-id value.  Channels with a defined tvg-id from the source m3u playlist do not encounter this issue.

**Comment by jaretclifton** [comment]
Can confirm I'm still seeing the same behavior in 1.2.8

**Comment by Fyb3roptik** [comment]
check 1.2.9

**Comment by jaretclifton** [comment]
Upgraded to 1.2.9 and the issue is still there. Renaming succeeds and sticks if I navigate around the UI. The moment a refresh of the page is initiated, the real channel names (existing prior to renaming) reappear.

**Comment by theharumph** [comment]
Also seeing the same thing as above in 1.2.9.  I've tried to remove the filter and readd with the live channel box checked.  Channel names that have a tvg-id starting with "threadfin" are still reverting back to the source m3u name after a page refresh.  As far as I can tell, channels that have a tvg-id flag in the original source are not affected.
