### ISSUE TITLE
Threadfin Crashing on Channel play using FFMPG buffer

### ISSUE THREAD

**Issue by iceman73** [Threadfin/Threadfin#426]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Latest Release is still crashing threadfin when trying to play a channel in Plex or tivimate

**Server (please complete the following information):**
- OS Linux
- Arch Intel 64 Bit
- Threadfin Version and Build 1.2.15

**To Reproduce**
1. Go to Open any channel in plex or Tivimate and as soon as it goes to buffer I get the following error

> 2024/10/25 09:00:36 [Threadfin] Client User-Agent:      Lavf/LIBAVFORMAT_VERSION
> 
> 2024/10/25 09:00:36 http: panic serving 192.168.94.44:35210: interface conversion: interface {} is nil, not string
> 
> goroutine 101 [running]:
> 
> net/http.(*conn).serve.func1()
> 
> 	/usr/local/go/src/net/http/server.go:1825 +0xbf
> 
> panic({0x83e020, 0xc00473a300})
> 
> 	/usr/local/go/src/runtime/panic.go:844 +0x258
> 
> threadfin/src.bufferingStream({0xc023c06e10, 0x14}, {0xc04795d6e0, 0x24}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...)
> 
> 	/src/src/buffer.go:183 +0x1e65
> 
> threadfin/src.Stream({0x9f6790, 0xc01aab80e0}, 0xc01a3f2300)
> 
> 	/src/src/webserver.go:185 +0x938
> 
> net/http.HandlerFunc.ServeHTTP(0x7f25186790f8?, {0x9f6790?, 0xc01aab80e0?}, 0x40efe5?)
> 
> 	/usr/local/go/src/net/http/server.go:2084 +0x2f
> 
> net/http.(*ServeMux).ServeHTTP(0x0?, {0x9f6790, 0xc01aab80e0}, 0xc01a3f2300)
> 
> 	/usr/local/go/src/net/http/server.go:2462 +0x149
> 
> net/http.serverHandler.ServeHTTP({0xc007152990?}, {0x9f6790, 0xc01aab80e0}, 0xc01a3f2300)
> 
> 	/usr/local/go/src/net/http/server.go:2916 +0x43b
> 
> net/http.(*conn).serve(0xc0000b8a00, {0x9f6b38, 0xc007554960})
> 
> 	/usr/local/go/src/net/http/server.go:1966 +0x5d7
> 
> created by net/http.(*Server).Serve
> 
> 	/usr/local/go/src/net/http/server.go:3071 +0x4db
> 

**Expected behavior**
Not to crash

**Comment by iceman73** [comment]
I think I fixed my own issue.

I had to go into each playlist and resave with the ffmpg buffer selected and Threadfin stopped crashing.

May want to add this to the upgrade notes for this version, or resave with default buffer settings for each playlist upon upgrade of the db

**Comment by jeffmur** [comment]
Thank you! This resolved my issue as well. I was on version 1.2.9, ran into this issue, upgraded to 1.2.15, issue persisted.

Playlist -> Save. Playback is fixed
