### ISSUE TITLE
Error parsing ppv stations on dummy data to desc / title on channel

### ISSUE THREAD

**Issue by lephino** [Threadfin/Threadfin#451]
Latest version of threadfin is producing the following lines in the log for any and all of my ppv stations:

syntax () - EC: 0
2024/11/15 22:36:50 [Threadfin] Create Dummy Guide:     Time offset -0700 - F1: Schumacher (Haas F1 Team)
2024/11/15 22:36:50 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0
2024/11/15 22:36:50 [Threadfin] Create Dummy Guide:     Time offset -0700 - NHL 09 10:00 PM | NEW YORK ISLANDERS VS VANCOUVER CANUCKS
2024/11/15 22:36:50 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-b5f48807fdd372b01d0304429be88152": invalid syntax () - EC: 0
2024/11/15 22:36:50 [Threadfin] Create Dummy Guide:     Time offset -0700 - F1: Perez (Red Bull Racing)
2024/11/15 22:36:50 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0
2024/11/15 22:36:50 [Threadfin] Create Dummy Guide:     Time offset -0700 - ESPN Plus 017
2024/11/15 22:36:50 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0
2024/11/15 22:36:50 [Threadfin] Create Dummy Guide:     Time offset -0700 - ESPN Plus 018
2024/11/15 22:36:50 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0
2024/11/15 22:36:50 [Threadfin] Create Dummy Guide:     Time offset -0700 - UFC 08:
2024/11/15 22:36:50 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-bc03fb9e224b42a0b6916c1a0d5ac937": invalid syntax () - EC: 0
2024/11/15 22:36:50 [Threadfin] Create Dummy Guide:     Time offset -0700 - F1: Leclerc (Ferrari)
2024/11/15 22:36:50 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0
2024/11/15 22:36:50 [Threadfin] Create Dummy Guide:     Time offset -0700 - NFL  | 02   1PM Packers at Bears
2024/11/15 22:36:50 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-30492b6506c1f728e7ca741f4785556c": invalid syntax () - EC: 0
2024/11/15 22:36:50 [Threadfin] Create Dummy Guide:     Time offset -0700 - ESPN Plus 019
2024/11/15 22:36:50 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0
2024/11/15 22:36:50 [Threadfin] Create Dummy Guide:     Time offset -0700 - NFL 02: Packers @ bears // UK Sun 17 Nov 5:58pm // ET Sun 17 Nov 12:58pm
2024/11/15 22:36:50 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0
2024/11/15 22:36:50 [Threadfin] Create Dummy Guide:     Time offset -0700 - NHL | 16
2024/11/15 22:36:50 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-cb91a621bd6a8b4cedac7fd38baa1656": invalid syntax () - EC: 0

Version:
31:15 [Threadfin] Version:                1.2 Build: 15
2024/11/15 22:31:15 [Threadfin] Database Version:       0.5.0

Linux based running via docker on x86

**Comment by lephino** [comment]
Still getting this error on 2.16, here's the updated lines:

2024/11/17 10:28:02 [Threadfin] Version:                1.2 Build: 16

2024/11/17 10:28:02 [Threadfin] Database Version:       0.5.0

2024/11/17 10:28:02 [Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 0



2024/11/17 10:35:45 [Threadfin] Create Dummy Guide:     Time offset -0700 - NHL 13 09:00 PM | PITTSBURGH PENGUINS VS CALGARY FLAMES

2024/11/17 10:35:45 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-b5f48807fdd372b01d0304429be88152": invalid syntax () - EC: 0

2024/11/17 10:35:45 [Threadfin] Create Dummy Guide:     Time offset -0700 - PPV 11: No Scheduled Event

2024/11/17 10:35:45 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-bc03fb9e224b42a0b6916c1a0d5ac937": invalid syntax () - EC: 0

2024/11/17 10:35:45 [Threadfin] Create Dummy Guide:     Time offset -0700 - ESPN Plus 030

2024/11/17 10:35:45 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0

2024/11/17 10:35:45 [Threadfin] Create Dummy Guide:     Time offset -0700 - NBA TV

2024/11/17 10:35:45 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0

2024/11/17 10:35:45 [Threadfin] Create Dummy Guide:     Time offset -0700 - NFL 08: Vikings @ titans // UK Sun 17 Nov 5:58pm // ET Sun 17 Nov 12:58pm

2024/11/17 10:35:45 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0

2024/11/17 10:35:45 [Threadfin] Create Dummy Guide:     Time offset -0700 - Peacock  1

2024/11/17 10:35:45 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0

2024/11/17 10:35:45 [Threadfin] Create Dummy Guide:     Time offset -0700 - NBA 15 : Mavericks vs Jazz // Friday 15/11 02:00am UK // Thursday 14/11 09:00pm ET

2024/11/17 10:35:45 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0

2024/11/17 10:35:45 [Threadfin] Create Dummy Guide:     Time offset -0700 - F1: Data

2024/11/17 10:35:45 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0

**Comment by Fyb3roptik** [comment]
Fixed in 1.2.16

**Comment by lephino** [comment]
I'm still getting this error, even on 1.2.18:

2024/11/18 16:10:04 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0

2024/11/18 16:10:04 [Threadfin] Create Dummy Guide:     Time offset -0700 - ESPN Plus 017

2024/11/18 16:10:04 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0

2024/11/18 16:10:04 [Threadfin] Create Dummy Guide:     Time offset -0700 - PPV 04: UFC 309 Jones v Miocic Main Card (11.16 10:00PM ET)

2024/11/18 16:10:04 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-bc03fb9e224b42a0b6916c1a0d5ac937": invalid syntax () - EC: 0

2024/11/18 16:10:04 [Threadfin] Create Dummy Guide:     Time offset -0700 - PPV 07: Ramirez v Smith (11.16 5:30PM ET)

2024/11/18 16:10:04 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-bc03fb9e224b42a0b6916c1a0d5ac937": invalid syntax () - EC: 0

and here's the version header from the logs:

For help run: /home/threadfin/bin/threadfin -h

2024/11/18 16:04:28 [Threadfin] [WARNING] Don't run this as Root!

2024/11/18 16:04:28 [Threadfin] Version:                1.2 Build: 18

2024/11/18 16:04:28 [Threadfin] Database Version:       0.5.0

2024/11/18 16:04:28 [Threadfin] System IP Addresses:    IPv4: 9 | IPv6: 11

2024/11/18 16:04:28 [Threadfin] Hostname:               {masked}

2024/11/18 16:04:28 [Threadfin] System Folder:          /data/conf/

2024/11/18 16:04:28 [Threadfin] Load Settings:          /data/conf/settings.json

2024/11/18 16:04:28 [Threadfin] Temporary Folder:       /tmp/threadfin/{masked}

2024/11/18 16:04:28 [Threadfin] GitHub:                 https://github.com/Threadfin

2024/11/18 16:04:28 [Threadfin] Git Branch:             Main [Threadfin]

2024/11/18 16:04:28 [Threadfin] SSDP / DLNA:            true

2024/11/18 16:04:28 BRANCH:  Main

2024/11/18 16:04:28 TAG LATEST:  1.2.18

2024/11/18 16:04:28 FILE:  https://github.com/Threadfin/Threadfin/releases/download/1.2.18/Threadfin_linux_amd64

2024/11/18 16:04:28 [Threadfin] UUID:                  {masked}

2024/11/18 16:04:28 [Threadfin] Tuner (Plex / Emby):    2

2024/11/18 16:04:28 [Threadfin] EPG Source:             XEPG

2024/11/18 16:04:28 [Threadfin] Plex Channel Limit:     480

2024/11/18 16:04:28 [Threadfin] Unfiltered Chan. Limit: 480

2024/11/18 16:04:28 [Threadfin] Backup Path:            /data/conf/backup/

2024/11/18 16:09:45 [Threadfin] Backup file:            /data/conf/backup/threadfin_auto_backup_20241118_1604.zip

**Comment by lephino** [comment]
Did you want me to open this as a new issue?
